// ─── Bracket projection DTOs ─────────────────────────────────────────────────
// Display-only projection generated by the backend from match data.
// No editable bracket, no separate bracket collection, no drag/drop contract.
// Bracket read access uses the tournament.match.read permission policy.

export interface BracketParticipantSeedDto {
  readonly participantId: string;
  readonly displayName: string;
  readonly seed: number;
}

export interface BracketMatchNodeDto {
  readonly matchId: string;
  readonly round: number;
  readonly matchNumber: number;
  readonly participant1?: BracketParticipantSeedDto;
  readonly participant2?: BracketParticipantSeedDto;
  readonly winnerId?: string;
  readonly status: string;
}

export interface BracketRoundDto {
  readonly round: number;
  readonly label: string;
  readonly matches: readonly BracketMatchNodeDto[];
}

export interface BracketProjectionDto {
  readonly tournamentId: string;
  readonly format: string;
  readonly rounds: readonly BracketRoundDto[];
  readonly generatedAt: string;
}
